smsGateway:
  allowedPhoneNumbers:
    - '${SMS_GATEWAY_ALLOWED_PHONE_NUMBERS_1}'
  provider:
   id: nexmo
   key: '${NEXMO_KEY}'
   secret: '${NEXMO_SECRET}'
   signatureSecret: '${NEXMO_SIGNATURE_SECRET}'
   phoneNumber: '${NEXMO_PHONE_NUMBER}'

weather:
  id: darksky
  apiKey: '${WEATHER_DARKSKY_API_KEY}'

cyclocity:
  id: jcdecaux
  apiKey: '${CYCLOCITY_JCDECAUX_API_KEY}'

navitia:
  id: navitia
  apiKey: '${navitia_API_KEY}'

preferences:
  - phoneNumber: '${SMS_GATEWAY_ALLOWED_PHONE_NUMBERS_1}'
    aliases:
      - key: bicloo
        value: 'bicloo gare maritime'
    defaults:
      timeZoneId: 'Europe/Paris'
      locale: 'en_US'
      country: 'FR'
      city: 'Nantes'
      rss: 'https://www.lemonde.fr/rss/une.xml'
